name: gallery

services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  tests-and-checks:
    build: 
      context: .
      target: tests-and-checks
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A gallery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  web:
    build: 
      context: .
      target: app
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=gallery.settings
      - DAJNGO_SECRET_KEY=django-insecure-c70zv04xefhq95!$#tgfik(0ipga_&1870uxtu&o!@s@&
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - celery
    command: bash -c "python manage.py migrate && python manage.py ensure_admin &&  gunicorn gallery.wsgi:application --bind 0.0.0.0:8001"

volumes:
  postgres_data:
